

def main():
    raise Exception(1)